import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  { path: '', loadChildren: './tabs/tabs.module#TabsPageModule' },
  { path: 'fruits', loadChildren: './fruits/fruits.module#FruitsPageModule' },
  { path: 'animals', loadChildren: './animals/animals.module#AnimalsPageModule' },
  { path: 'colors', loadChildren: './colors/colors.module#ColorsPageModule' },
  { path: 'numbers', loadChildren: './numbers/numbers.module#NumbersPageModule' },
  { path: 'abecedario', loadChildren: './abecedario/abecedario.module#AbecedarioPageModule' },
  { path: 'letra-a', loadChildren: './letra-a/letra-a.module#LetraAPageModule' },
  { path: 'b', loadChildren: './b/b.module#BPageModule' },
  { path: 'c', loadChildren: './c/c.module#CPageModule' },
  { path: 'd', loadChildren: './d/d.module#DPageModule' },
  { path: 'e', loadChildren: './e/e.module#EPageModule' },
  { path: 'f', loadChildren: './f/f.module#FPageModule' },
  { path: 'g', loadChildren: './g/g.module#GPageModule' },
  { path: 'h', loadChildren: './h/h.module#HPageModule' },
  { path: 'i', loadChildren: './i/i.module#IPageModule' },
  { path: 'j', loadChildren: './j/j.module#JPageModule' },
  { path: 'k', loadChildren: './k/k.module#KPageModule' },
  { path: 'l', loadChildren: './l/l.module#LPageModule' },
  { path: 'm', loadChildren: './m/m.module#MPageModule' },
  { path: 'n', loadChildren: './n/n.module#NPageModule' },
  { path: 'o', loadChildren: './o/o.module#OPageModule' },
  { path: 'p', loadChildren: './p/p.module#PPageModule' },
  { path: 'q', loadChildren: './q/q.module#QPageModule' },
  { path: 'r', loadChildren: './r/r.module#RPageModule' },
  { path: 's', loadChildren: './s/s.module#SPageModule' },
  { path: 't', loadChildren: './t/t.module#TPageModule' },
  { path: 'u', loadChildren: './u/u.module#UPageModule' },
  { path: 'v', loadChildren: './v/v.module#VPageModule' },
  { path: 'w', loadChildren: './w/w.module#WPageModule' },
  { path: 'x', loadChildren: './x/x.module#XPageModule' },
  { path: 'y', loadChildren: './y/y.module#YPageModule' },
  { path: 'z', loadChildren: './z/z.module#ZPageModule' },
  { path: 'perro', loadChildren: './perro/perro.module#PerroPageModule' },
  { path: 'gato', loadChildren: './gato/gato.module#GatoPageModule' },
  { path: 'gallina', loadChildren: './gallina/gallina.module#GallinaPageModule' },
  { path: 'cerdo', loadChildren: './cerdo/cerdo.module#CerdoPageModule' },
  { path: 'vaca', loadChildren: './vaca/vaca.module#VacaPageModule' },
  { path: 'conejo', loadChildren: './conejo/conejo.module#ConejoPageModule' },
  { path: 'loro', loadChildren: './loro/loro.module#LoroPageModule' },
  { path: 'zero', loadChildren: './zero/zero.module#ZeroPageModule' },
  { path: 'one', loadChildren: './one/one.module#OnePageModule' },
  { path: 'two', loadChildren: './two/two.module#TwoPageModule' },
  { path: 'three', loadChildren: './three/three.module#ThreePageModule' },
  { path: 'four', loadChildren: './four/four.module#FourPageModule' },
  { path: 'five', loadChildren: './five/five.module#FivePageModule' },
  { path: 'six', loadChildren: './six/six.module#SixPageModule' },
  { path: 'seven', loadChildren: './seven/seven.module#SevenPageModule' },
  { path: 'eigth', loadChildren: './eigth/eigth.module#EigthPageModule' },
  { path: 'nine', loadChildren: './nine/nine.module#NinePageModule' },
  { path: 'ten', loadChildren: './ten/ten.module#TenPageModule' },
  { path: 'azul', loadChildren: './azul/azul.module#AzulPageModule' },
  { path: 'rojo', loadChildren: './rojo/rojo.module#RojoPageModule' },
  { path: 'verde', loadChildren: './verde/verde.module#VerdePageModule' },
  { path: 'amarillo', loadChildren: './amarillo/amarillo.module#AmarilloPageModule' },
  { path: 'blanco', loadChildren: './blanco/blanco.module#BlancoPageModule' },
  { path: 'negro', loadChildren: './negro/negro.module#NegroPageModule' },
  { path: 'morado', loadChildren: './morado/morado.module#MoradoPageModule' },
  { path: 'rosado', loadChildren: './rosado/rosado.module#RosadoPageModule' },
  { path: 'banano', loadChildren: './banano/banano.module#BananoPageModule' },
  { path: 'cereza', loadChildren: './cereza/cereza.module#CerezaPageModule' },
  { path: 'coco', loadChildren: './coco/coco.module#CocoPageModule' },
  { path: 'fresa', loadChildren: './fresa/fresa.module#FresaPageModule' },
  { path: 'limon', loadChildren: './limon/limon.module#LimonPageModule' },
  { path: 'manzana', loadChildren: './manzana/manzana.module#ManzanaPageModule' },
  { path: 'naraja', loadChildren: './naraja/naraja.module#NarajaPageModule' },
  { path: 'pineapple', loadChildren: './pineapple/pineapple.module#PineapplePageModule' },
  { path: 'uva', loadChildren: './uva/uva.module#UvaPageModule' },
  { path: 'sandia', loadChildren: './sandia/sandia.module#SandiaPageModule' }
];
@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}
